baseURL = 'https://kilaura-tribe.github.io/myblog/'
languageCode = 'ru'
title = 'My and You Veri Osint'
theme = 'PaperMod'

[params.homeInfoParams]
    Title = "Привет! Я интересуюсь OSINT 🔍"
    Content = "Здесь я делюсь гайдами по Termux и результатами расследований."

#[[params.socialIcons]]
#    name = "github"
#    url = "https://github.com/ваш-профиль"
#[[params.socialIcons]]
#    name = "telegram"
#    url = "https://t.me/ваш-ник"

