baseURL = 'https://kilaura-tribe.github.io/myblog/'
languageCode = 'ru'
title = 'My and You Very Osint'
publishDir = "docs"
theme = 'PaperMod'

[params]
    env = "production"
    title = "Albert Kabuu | OSINT"
    mainSections = ["posts", "log"]
    
    [params.label]
        text = "🔍 KABUU_LOGS"
        icon = "/apple-touch-icon.png" # Это подтянет стандартную иконку, если она есть

#[[params.socialIcons]]
#    name = "github"
#    url = "https://github.com/ваш-профиль"
#[[params.socialIcons]]
#    name = "telegram"
#    url = "https://t.me/ваш-ник"

    mainSections = ["posts", "log"]    
    showCodeCopyButtons = true
[menu]
[[menu.main]]
    identifier = "tools"
    name = "Арсенал"
    url = "/tools/"
    weight = 15
[[menu.main]]
    identifier = "log"
    name = "Расследования"
    url = "/log/"
    weight = 25
    [[menu.main]]
        identifier = "osint"
        name = "OSINT"
        url = "/tags/osint/"
        weight = 10
    [[menu.main]]
        identifier = "termux"
        name = "Termux"
        url = "/tags/termux/"
        weight = 20
    [[menu.main]]
        identifier = "hardware"
        name = "Железо"
        url = "/tags/hardware/"
        weight = 30    
[[menu.main]]
        identifier = "search"
        name = "Поиск"
        url = "/search/"
        weight = 40
[markup.goldmark.renderer]
    unsafe = true

